name: waspadaai
description: AI-powered scam and hoax detector for Indonesian users.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  google_fonts: ^8.1.0
  http: ^1.2.0
  lottie: ^3.1.0
  google_generative_ai: ^0.4.7
  image_picker: ^1.2.2
  file_picker: ^11.0.2
  mime: ^2.0.0
  archive: ^3.6.1
  crypto: ^3.0.5
  shared_preferences: ^2.5.5
  url_launcher: ^6.3.0
  xml: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/bg_video.mp4
